fix: Fix missing header
Fix compiler error on deepin v20 from source:
error: ‘bindtextdomain’ was not declared in this scope
error: ‘textdomain’ was not declared in this scope